name: Test FrontEnd
run-name: Testing React Elements
on:
  pull_request:
    branches:
      - main
    types:
      - opened
jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Copy Files to WorkSpace
        uses: actions/checkout@v4
      - name: Install Modules
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm i

  test:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - run: npm run test
